# Noctalia Template for Starship

format = "[󱄅](bold {{colors.primary.default.hex}}) $directory$git_branch$git_status$character"

[character]
success_symbol = "[❯](bold {{colors.primary.default.hex}})"
error_symbol = "[❯](bold {{colors.error.default.hex}})"

[directory]
style = "bold {{colors.secondary.default.hex}}"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold {{colors.tertiary.default.hex}}"

[git_status]
style = "bold {{colors.error.default.hex}}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
